export const PREFIX_CLS = 'mhrise'

export const PRIMARY_COLOR = '#5d5d99'

export const USER_THEME_STORE_KEY = 'USER_THEME_STORE_KEY'

export const USER_COMPACT_MODE_STORE_KEY = 'USER_COMPACT_MODE_STORE_KEY'

export const USER_VERSION_STORE_KEY = 'USER_VERSION_STORE_KEY'

export const USER_CART_STORE_KEY = 'USER_CART_STORE_KEY'

export const USER_LOCALE_STORE_KEY = 'USER_LOCALE_STORE_KEY'
